/*
=========================================================================
						 Magnitude Analysis
=========================================================================
Project: SQL Server Data Analytics Project
Script: 06_Magnitude_Analysis.sql
Author: Abdul Muqtadeer Baag

Purpose:
	- Analyze the magnitude of data across key dimensions.
	- To understand distribution and contribution.

SQL Server Functions used:
	- COUNT()
	- SUM()
	- AVG()
	- GROUP BY
	- ORDER BY
==========================================================================
*/

-- Change the DB context:
USE AnalyticsDB;
GO

-- Find total customers by countries:
SELECT
    Country,
    COUNT(Customer_Key) AS Total_Customers
FROM final.dim_customers
GROUP BY Country
ORDER BY Total_Customers DESC;
GO

-- Find total customers by gender:
SELECT
    Gender,
    COUNT(Customer_Key) AS Total_Customers
FROM final.dim_customers
GROUP BY Gender
ORDER BY Total_Customers DESC;
GO

-- Find total products by category:
SELECT
    Category,
    COUNT(Product_Key) AS Total_Products
FROM final.dim_products
GROUP BY Category
ORDER BY Total_Products DESC;
GO

-- What is the average costs in each category:
SELECT
	Category,
    AVG(Cost) AS Avg_Cost
FROM final.dim_products
GROUP BY Category
ORDER BY Avg_Cost DESC;
Go

-- What is the total revenue generated for each category:
SELECT
    p.Category,
    SUM(f.Sales_Amount) AS Total_Revenue
FROM final.fact_sales f
LEFT JOIN final.dim_products p
    ON p.Product_Key = f.Product_Key
GROUP BY p.Category
ORDER BY Total_Revenue DESC;
GO

-- What is the total revenue generated by each customer:
SELECT
    c.Customer_Key,
    c.First_Name,
    c.Last_Name,
    SUM(f.Sales_Amount) AS Total_Revenue
FROM final.fact_sales f
LEFT JOIN final.dim_customers c
    ON c.Customer_Key = f.Customer_Key
GROUP BY 
    c.Customer_Key,
    c.First_Name,
    c.Last_Name
ORDER BY Total_Revenue DESC;
GO

-- What is the distribution of sold items across countries:
SELECT
    c.Country,
    SUM(f.Quantity) AS Total_Sold_Items
FROM final.fact_sales f
LEFT JOIN final.dim_customers c
    ON c.Customer_Key = f.Customer_Key
GROUP BY c.Country
ORDER BY Total_Sold_Items DESC;
GO
